Update GraphBuilder to use AdjacencyList
FEniCS/dolfinx pull request #1132
Opened 2020-09-16 18:54 UTC by IgorBaratta

2020-09-16 19:10 UTC, chrisrichardson approved these changes
looks good to me

2020-09-16 20:07 UTC, michalhabera approved these changes

2020-09-17 06:24 UTC, garth-wells requested changes
Looks good. Just one small suggestion in a comment.

2020-09-17 06:24 UTC, garth-wells commented on cpp/dolfinx/mesh/GraphBuilder.cpp
> +        facet[k] = cell_vertices.links(i)[facet_vertices(j, k)];
I'd suggest hoisting `auto foo = cell_vertices.links(i);` outside of the `j` and `k` loops.

2020-09-17 14:11 UTC, garth-wells approved these changes

2020-09-17 14:32 UTC, merged