Fix 3D plotting with matplotlib
FEniCS/dolfinx pull request #1158
Opened 2020-10-10 10:41 UTC by jorgensd

3D plotting with dolfinx and matplotlib has not been working for a long time due to the lack of boundary mesh, along with an update in matplotlib, yielding the following error:
```
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes
```
when running:
```
import matplotlib.pyplot as plt
from dolfinx.plotting import plot
from dolfinx import UnitCubeMesh
from mpi4py import MPI

mesh = UnitCubeMesh(MPI.COMM_WORLD, 3, 3, 3)
plot(mesh, color="w", shade=True, edgecolors="b")

plt.savefig("mesh.png")
```
This fix utilizes #1139 to restore plotting of 3D meshes.

2020-10-10 17:13 UTC, jmv2009 commented
I'm just removing the offending "ax.set_aspect('equal')" from plotting.py to fix this.

2020-10-10 19:11 UTC, jorgensd commented
> I'm just removing the offending "ax.set_aspect('equal')" from plotting.py to fix this.
As the boundary mesh class is not existing in dolfinx, the code path of tdim=3, gdim=3 will not run even if you remove the set_aspect. Therefore I have moved my helper function from a test into dolfinx.mesh to cope with this.

2020-10-12 08:45 UTC, garth-wells commented
Maybe we should just remove Matplotlib and use vedo and/or pvista instead? See #1159.

2020-10-12 08:50 UTC, jorgensd commented
> Maybe we should just remove Matplotlib and use vedo and/or pvista instead? See #1159.

I can give vedo a go

2020-10-12 11:46 UTC, jorgensd commented
> Maybe we should just remove Matplotlib and use vedo and/or pvista instead? See #1159. 

I think we should merge this, and then think about #1159 (and not add any more effort into matplotlib)

2020-10-14 09:23 UTC, garth-wells requested changes

2020-10-14 09:23 UTC, garth-wells commented on python/dolfinx/mesh.py
> +def create_boundary_mesh(mesh, comm, orient=False):
Let's put this back in the plotting module. We don't want to encourage its use without careful thought.

2020-10-22 06:52 UTC, garth-wells approved these changes

2020-10-22 06:52 UTC, merged