Interpolation of functions into abritrary spaces
FEniCS/dolfinx pull request #1388
Opened 2021-02-05 15:13 UTC by mscroggs

Using the mapping information that basix provides directly, we can now interpolation into an arbitrary space.

2021-02-05 15:56 UTC, jorgensd commented on cpp/dolfinx/fem/FiniteElement.h
> +  /// @param[in] cell_permutation Permutation data fro the cell
Typo.

2021-02-05 16:07 UTC, jorgensd commented on python/test/unit/function/test_interpolation.py
> +    print(ordered_points, cells)
Remove print

2021-02-05 16:07 UTC, jorgensd commented on python/test/unit/function/test_interpolation.py
> +        print(v.vector[d])
Remove print

2021-02-08 10:17 UTC, garth-wells requested changes

2021-02-08 10:17 UTC, garth-wells commented on cpp/dolfinx/fem/FiniteElement.cpp
> +void FiniteElement::map_push_forward(
I's suggest templating these functions on the C++ side, see https://github.com/FEniCS/dolfinx/blob/master/cpp/dolfinx/fem/FiniteElement.h#L187.

2021-02-18 12:14 UTC, closed without merging