Expose dof permutation bools
FEniCS/dolfinx pull request #1580
Opened 2021-06-21 11:09 UTC by jorgensd

Expose booleans required for python assemblers

2021-06-21 12:15 UTC, mscroggs approved these changes

2021-06-22 06:32 UTC, garth-wells requested changes
I think the both the functions should be properties, i.e.
```cpp
.def_property_readonly("needs_facet_permutations", &dolfinx::fem::Form<PetscScalar>::needs_facet_permutations)
```

2021-06-22 08:34 UTC, jorgensd commented
> I think the both the functions should be properties, i.e.
> 
> ```c++
> .def_property_readonly("needs_facet_permutations", &dolfinx::fem::Form<PetscScalar>::needs_facet_permutations)
> ```

Fixed

2021-06-22 08:57 UTC, garth-wells approved these changes

2021-06-22 09:12 UTC, merged