Fix function copy option
FEniCS/dolfinx pull request #1916
Opened 2022-01-06 16:37 UTC by jorgensd

Resolves #1912

2022-01-06 17:35 UTC, garth-wells requested changes
Looks good. Could we add a test that would have picked up the issue?

2022-01-07 06:45 UTC, francesco-ballarin approved these changes

2022-01-07 07:06 UTC, jorgensd commented
> Looks good. Could we add a test that would have picked up the issue?

Test added

2022-01-07 07:15 UTC, garth-wells approved these changes

2022-01-07 08:04 UTC, merged