Replace discrete operator with arbitrary order operator
FEniCS/dolfinx pull request #2051
Opened 2022-03-09 10:34 UTC by jorgensd

Create general matrix operator $G$ mapping $u\in P^k/Q^k \mapsto  \nabla \phi \in ND_k$.

Generalizes the previous discrete operator, and works for arbitrary order spaces.

2022-03-09 10:45 UTC, jpdean commented
Great! This functionality is very useful for solving Maxwell's equations. I'll look at this PR in detail tonight.

It would also be good to implement the discrete curl and discrete divergence operators too at some point in the future.

2022-03-09 10:54 UTC, jorgensd commented
> Great! This functionality is very useful for solving Maxwell's equations. I'll look at this PR in detail tonight.
> 
> It would also be good to implement the discrete curl and discrete divergence operators too at some point in the future.

I'll start by implementing the vector Lagrange->Nedelec operator, ref: https://hypre.readthedocs.io/en/latest/solvers-ams.html#high-order-discretizations

The gradient operator has some neat tricks to it, as the inverse covariant piola makes the contribution only dependent on the dof transformation, and not the jacobian, inverse jacobian and detJ.

It would be useful if you could make a list of what operators (and between what spaces) we need for different solvers, it would be very helpful. I guess they follow the de Rahm complex https://defelement.com/de-rham.html

2022-03-09 13:09 UTC, garth-wells requested changes
Looks good. Let's iterate on it a bit.

2022-03-09 13:09 UTC, garth-wells commented on cpp/dolfinx/fem/discreteoperators.h
> +  // Create element kernel
This comment is a bit vague.

In general, comments should have a black line before them for readability.

2022-03-09 13:09 UTC, garth-wells commented on cpp/dolfinx/fem/discreteoperators.h
> +      = {(std::size_t)tdim + 1, X.shape(0), (std::size_t)ndofs_cell_1,
Use `std::size_t` for the variable to reduce the boiler plate code.

2022-03-09 13:09 UTC, garth-wells commented on cpp/dolfinx/fem/discreteoperators.h
> +  auto l_dphi
Better variable name?

2022-03-09 13:09 UTC, garth-wells commented on cpp/dolfinx/fem/discreteoperators.h
> +  // Compute local element interpolation matrix
// Get the element interpolation matrix

2022-03-09 13:09 UTC, garth-wells commented on cpp/dolfinx/fem/discreteoperators.h
> +  // Get inverse transform
// Get inverse DOF transform function

2022-03-09 13:09 UTC, garth-wells commented on python/test/unit/fem/test_discrete_operators.py
> +def test_interpolation_matrix(cell_type, p):
Can a parallel check be added? Even if just on the Hypre AMS iteration count.

2022-03-09 13:09 UTC, garth-wells commented on cpp/dolfinx/fem/discreteoperators.h
> +  // Tabulate Lagrange space at H(curl) interpolation points
Break up steps with comments. Looks like first step is getting the interpolation points for Lagrange element.

2022-03-09 14:44 UTC, garth-wells commented
I think the strings checks should be removed and replaced with a clear warning in the doc strings.

Strings are fragile and it introduced more work for later to remove them.

2022-03-09 15:12 UTC, jorgensd commented
> I think the string checks should be removed and replaced with a clear warning in the doc strings.
> 
> Strings are fragile and it introduced more work for later to remove them. We don't need to protect the user from themselves for advanced functionality.

What about the following:
- We check that the mapping-type of the output space is the covariant piola map
- We check that the mapping-type of the input space is the identity
The whole code relies on these assumptions, and would produce garbage if this is not true.
We can get this using `dolfinx::fem::FiniteElement::map_type` (https://github.com/FEniCS/dolfinx/blob/9d11d4408975b8b959be19f4b6c0f08cf4e289a7/cpp/dolfinx/fem/FiniteElement.h#L182)

2022-03-09 15:36 UTC, jorgensd commented
> > What about the following:
> > 
> > * We check that the mapping-type of the output space is the covariant piola map
> > * We check that the mapping-type of the input space is the identity
> >   The whole code relies on these assumptions, and would produce garbage if this is not true.
> >   We can get this using `dolfinx::fem::FiniteElement::map_type` (https://github.com/FEniCS/dolfinx/blob/9d11d4408975b8b959be19f4b6c0f08cf4e289a7/cpp/dolfinx/fem/FiniteElement.h#L182
> >   
> >   )
> 
> Anything but strings.
> 
> The point still holds that we don't need to stop a user from shooting themselves in the foot if they mis-use things. Most important is that the docs state the preconditions.

I've added a suggest documentation and assertion.

2022-03-14 12:35 UTC, garth-wells commented on cpp/dolfinx/fem/discreteoperators.h
>  la::SparsityPattern
This seems like just a re-implementation of `fem::sparsitybuild::cells`, and it doesn't see to exploit any special non-zero structure for the discrete gradient problem.

2022-03-14 16:18 UTC, jorgensd commented on cpp/dolfinx/fem/discreteoperators.h
> +/// @param[in] V1 A Lagrange space
@garth-wells should we say:
```
V1 A scalar Lagrange space
```
?

2022-03-14 22:10 UTC, jorgensd commented on cpp/dolfinx/fem/discreteoperators.h
> +/// The discrete gradient operator \f$A\f$ interpolates take the
This sentence doesn’t sound quite right anymore.
`…  \f$A\f$ interpolates take the …`

2022-03-14 22:56 UTC, garth-wells approved these changes

2022-03-14 23:24 UTC, merged