Add non-recursive collision algorithm
FEniCS/dolfinx pull request #2125
Opened 2022-04-12 22:28 UTC by IgorBaratta

Also remove some expensive xtensor computations, and avoid allocating intermediate arrays.

```python
import dolfinx.mesh
import ufl

from dolfinx import geometry
from dolfinx import common
from dolfinx import fem
from mpi4py import MPI

comm = MPI.COMM_WORLD
mesh = dolfinx.mesh.create_unit_cube(comm, 50, 50, 50)

el = ufl.FiniteElement("Lagrange", mesh.ufl_cell(), 2)
V = fem.FunctionSpace(mesh, el)

x = V.tabulate_dof_coordinates()

tree = geometry.BoundingBoxTree(mesh, mesh.geometry.dim)

with common.Timer("compute_collisions") as t:
    cell_candidates = geometry.compute_collisions(tree, x)

common.list_timings(comm, [common.TimingType.wall])
```

This branch:
``` 
compute_collisions                                                          |     1  1.582766  1.582766
```

main:
```
compute_collisions                                                          |     1  14.208511  14.208511
```

2022-04-13 14:40 UTC, jorgensd commented on cpp/dolfinx/geometry/utils.cpp
>  void _compute_collisions_point(
Maybe add in/out params with description here

2022-04-13 14:42 UTC, jorgensd commented on cpp/dolfinx/geometry/utils.cpp
> +        // the left subtree
```suggestion
        // If the point collides with the both child nodes, add the right node to the
        // stack (for later visiting) and continue the tree traversal with
        // the left subtree
```

2022-04-19 08:54 UTC, jorgensd commented on cpp/dolfinx/geometry/utils.cpp
> +      entities.push_back(bbox[1]);
```suggestion
    if (is_leaf(bbox))
    {
      // If box is a leaf node then add it to the list of colliding entities
      entities.push_back(bbox[1]);
    }
```

2022-04-19 08:55 UTC, jorgensd commented on cpp/dolfinx/geometry/utils.cpp
> +        next = bbox[0];
```suggestion
      {
        // Traverse the current node's left subtree
        next = bbox[0];
      }
```

2022-04-19 08:55 UTC, jorgensd commented on cpp/dolfinx/geometry/utils.cpp
> +        next = bbox[1];
```suggestion
      else if (right)
      {
        // Traverse the current node's right subtree
        next = bbox[1];
      }
```

2022-04-19 11:32 UTC, IgorBaratta commented
If this PR goes through, another one can follow doing the same thing with `_compute_collisions_tree`.

2022-04-20 09:48 UTC, garth-wells requested changes
Should we change some `xt::xtensor_fixed<double, xt::xshape<3>>` to `std::array<double, x>` if we're making less use of xtension functions?

2022-04-20 09:48 UTC, garth-wells commented on cpp/dolfinx/geometry/utils.cpp
> +    in &= x[i] >= (b(0, i) - eps);
Maybe add a brief explanation of what's happening?

2022-04-20 09:48 UTC, garth-wells commented on cpp/dolfinx/geometry/utils.cpp
> +    if (next == -1 && !stack.empty())
We generally use `and` rather than `&&`.

2022-04-20 09:59 UTC, jorgensd commented on cpp/dolfinx/geometry/utils.cpp
> +    if (next == -1 && !stack.empty())
```suggestion
    if (next == -1 and !stack.empty())
```

2022-04-20 13:13 UTC, jorgensd commented on cpp/dolfinx/geometry/utils.cpp
> +// bounding box, b(0,i) <= x[i] <= b(1,i) for i = 0, 1, 2
```suggestion
/// A point `x` is inside a bounding box `b` if each component of its coordinates
/// lies within the range `[b(0,i), b(1,i)]` that defines the bounds of the
/// bounding box, b(0,i) <= x[i] <= b(1,i) for i = 0, 1, 2
```

2022-04-20 13:14 UTC, jorgensd commented on cpp/dolfinx/geometry/utils.cpp
> +// a(0,i) <= b(1, i) and a(1,i) >= b(0, i)
```suggestion
/// A bounding box "a" is contained inside another bounding box "b", if each
/// of its intervals [a(0,i), a(1,i)] is contained in [b(0,i), b(1,i)],
/// a(0,i) <= b(1, i) and a(1,i) >= b(0, i)
```

2022-04-21 09:53 UTC, garth-wells approved these changes

2022-04-21 10:39 UTC, merged