Mscroggs/demos
FEniCS/dolfinx pull request #2140
Opened 2022-04-22 11:14 UTC by mscroggs

Added a Lagrange variants demo.

When built for the website the new demo looks something like this:
![new-demo](https://user-images.githubusercontent.com/9850599/164704084-46b352bb-26e4-487f-a754-b0bd2c759750.png)

2022-04-22 11:27 UTC, mscroggs commented
This new demo uses matplotlib to draw its plots, In https://github.com/FEniCS/dolfinx/pull/2140/commits/144a1dc7f5edd8a60f043f4b243f09a1e68e9d49, I've used a try except to allow the demo to run if matplotlib is not installed. I'm not sure if this is the best thing to do or not. Opinions?

2022-04-23 09:18 UTC, garth-wells requested changes
Looks great. I pushed some text edits.

I'd prefer to not add images to the repository. Could the figures be generated when the documentation is produced?

2022-04-23 09:58 UTC, mscroggs commented on python/demo/demo_lagrange_variants.py
> +try:
I've made the CIs install matplotlib in https://github.com/FEniCS/dolfinx/pull/2140/commits/7855b37fb935540e36b2aab2602d89708dd7ff71

2022-04-23 11:41 UTC, mscroggs commented
> I'd prefer to not add images to the repository. Could the figures be generated when the documentation is produced?

I believe this is now done

2022-04-26 09:37 UTC, garth-wells approved these changes

2022-04-26 09:37 UTC, merged