Interpolation between different meshes
FEniCS/dolfinx pull request #2245
Opened 2022-06-16 14:45 UTC by massimiliano-leoni

This pull request supersedes #1598 .
This pull request implements the same algorithm using the MPI Neighbourhood communication paradigm instead of the MPI One-sided communication one. The paradigm switch is joint work with @IgorBaratta .

2022-06-16 14:57 UTC, jorgensd commented on cpp/dolfinx/fem/interpolate.h
> +#include <xtensor/xio.hpp>
```suggestion
```

2022-06-16 15:07 UTC, massimiliano-leoni commented
![interpolation](https://user-images.githubusercontent.com/12351309/174101043-07054186-0f4b-41ce-b7b6-19aa4dc6c098.png)

And here's a cool picture, as requested by @IgorBaratta :D

2022-06-16 15:40 UTC, jorgensd commented on cpp/demo/interpolation/main.cpp
> +  const std::array<std::size_t, 3> subdivisions = {50, 50, 50};
We should reduce the sizes of these problems as they are demos

2022-06-16 15:41 UTC, jorgensd commented on cpp/demo/interpolation/main.cpp
> +  auto meshL = std::make_shared<mesh::Mesh>(mesh::create_box(
We could use `GhostMode::none` here as we do not do any interior integrals in this demo

2022-06-16 15:50 UTC, jorgensd commented on cpp/dolfinx/geometry/utils.cpp
> +#include <xtensor/xio.hpp>
```suggestion
```

2022-06-16 16:39 UTC, IgorBaratta commented
We've also added a few improvements in different bits of the code, for instance collision detection and tabulation, to make interpolation faster.

2022-06-28 05:40 UTC, garth-wells requested changes
This functionality is useful and very welcome. I think a more granular design would further improve the implementation. I suggest breaking it into distinct steps:

1. Code to find points on other ranks, i.e. a function that takes a list of points and returns the index of rank (indices of ranks) where the point can be found. Discussion points would include how to handle points on the boundary between partitions.
2. Pull back of points to the reference cell
3. Evaluating expression at points and sending back data to perform the interpolation

Breaking up the steps will support more efficient implementations (a common use case would be interpolating multiple times and a redesign would make this much more efficient) and make it easier to discuss specific design choices.

Something to also bear in mind is that we're working to minimise the use of `xtensor`, so avoid introducing it where possible.

2022-06-28 06:08 UTC, jorgensd commented
> This functionality is useful and very welcome. I think a more granular design would further improve the implementation. I suggest breaking it into distinct steps:
> 
> 1. Code to find points on other ranks, i.e. a function that takes a list of points and returns the index of rank (indices of ranks) where the point can be found. Discussion points would include how to handle points on the boundary between partitions.
> 2. Pull back of points to the reference cell
> 3. Evaluating expression at points and sending back data to perform the interpolation
> 
> Breaking up the steps will support more efficient implementations (a common use case would be interpolating multiple times and a redesign would make this much more efficient) and make it easier to discuss specific design choices. A PR for each step would be helpful.
> 
> Something to also bear in mind is that we're working to minimise the use of `xtensor`, so avoid introducing it where possible.

Ive suggested a breakdown into 5 steps in: https://github.com/massimiliano-leoni/dolfinx/pull/1. Could you have a look and see what you think?

2022-07-22 09:47 UTC, garth-wells requested changes
First pass over first part of the PR.

It would be good to update the PR with `main` before continuing. 

My feeling is that it would be easier to review this as a set of small PRs.

2022-07-22 09:47 UTC, garth-wells commented on cpp/demo/interpolation-io/CMakeLists.txt
> +set(CMAKE_INCLUDE_CURRENT_DIR ON)
Why has this been added? 

I don't see that the script that generates the CMake files has been updated.

2022-07-22 09:47 UTC, garth-wells commented on cpp/demo/interpolation/main.cpp
> +// Copyright (C) 2022 Igor A. Baratta and Massimiliano Leoni
Demo name isn't very informative. It's not clear what this demo is demonstrating.

2022-07-22 09:47 UTC, garth-wells commented on cpp/demo/interpolation/main.cpp
> +      auto r = xt::zeros_like(x);
Use xtensor to get row views, etc, and avoid loops.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +#include <xtensor/xadapt.hpp>
Avoid xtensor.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +/// @brief Send data from a set of processes to another set using neighborhod
". . . to another set of [what?]"

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +/// The data to send is structured as (src_ranks.size(), value_size), where the
Start with higher level opening of what is done, then how it's structured.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +xt::xtensor<T, 2> send_back_values(const MPI_Comm& comm,
Function name isn't very informative and is too generic.

Is it intended to be in the public interface?

Body of the function is very similar to code elsewhere. Should it be made a general utility function?

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +                                   const std::vector<std::int32_t>& src_ranks,
Use `std::span` rather than `std::vector` references.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +                                   const xt::xtensor<T, 2> send_values)
Avoid xtensor.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +/// @note It is assumed that src_ranks are already sorted.
Assumed or required? Use `@pre`.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +/// @param[in] src_ranks The rank owning the values of each row in send_values
Make description for precise, e.g. `ith entry is foo is ....`

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +/// @param[in] dest_ranks The rank each local point is receiving data from.
Description isn't clear.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +/// @note dest_ranks might contain -1 (no process owns the point)
Move note out of param list. Gets lost otherwise.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +  // Create neighborhood communicator from send back
What is 'send back'?

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +  // Strip dest ranks for all -1 entries
Comment doesn't quite make sense.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +  // Create unique set of sorted in ranks
in-ranks, otherwise meaning is different.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +  // Create communicator from processes with dof values to the processes
I don't think this function is specific to dofs.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +  // Compute map from incoming value to local point index
"Build map"?

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +  std::vector<std::int32_t> unpack_map;
Maybe a more meaningful name?

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +    std::map<std::int32_t, std::int32_t> rank_to_neighbor;
Best to avoid `std::maps`. Build vector of pairs, then sort and then use binary search.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +  // Compute sending offsets
```suggestion
  // Compute send offsets
```

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +
Close gap to make clear which code above comment corresponds to.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +    std::map<std::int32_t, std::int32_t> rank_to_neighbor;
Avoid `std::map`.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +  // Fill in values for interpolation points on local process
"integration points"?

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +namespace
Anonymous namespaces shouldn't be used in header files.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +  assert(mesh);
Use of assertions in this function is a bit random.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +  int result;
Use scoping to avoid leaking variables this are used very locally from entering the scope of the whole function.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +    if (auto mesh_v = v.function_space()->mesh(); mesh != mesh_v)
```suggestion
    if (auto mesh_v = v.function_space()->mesh(); mesh_v != mesh)
```

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +      if (*element1 == *element0)
```suggestion
      if (element1 == element0 or *element1 == *element0)
```

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/geometry/gjk.h
> +/// @note Avoid allocation of output, use input/output parameters instead.
I don't understand this comment.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/geometry/utils.cpp
> +    constexpr double eps2 = 1e-20;
This seems suspiciously small.

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/geometry/utils.cpp
> +      // Fix
Fix what?

2022-07-22 09:47 UTC, garth-wells commented on cpp/dolfinx/geometry/utils.cpp
> +        common::impl::copy_N<3>(std::next(geom_dofs.begin(), 3 * dofs[i]),
Braces missing.

2022-08-05 15:27 UTC, massimiliano-leoni commented
@garth-wells I updated with `main` and I applied all but two edits [I'm not sure what to do in those cases].

2022-10-19 08:13 UTC, mscroggs commented
I'd be keen for this to get merged, as there is some functionality in here that is needed for evaluating point sources, which is something I want to be able to use.

2022-10-21 13:09 UTC, merged