Slightly simplify submesh geometry creation
FEniCS/dolfinx pull request #2498
Opened 2023-01-04 16:32 UTC by jpdean

2023-01-04 16:40 UTC, garth-wells requested changes
Looks good, just one small style suggestion.

2023-01-04 16:40 UTC, garth-wells commented on cpp/dolfinx/mesh/Mesh.cpp
> +  submesh_x_dofmap_offsets.reserve(submesh_to_mesh_map.size() + 1);
I would raise this up one line, and follow it by `submesh_x_dofmap_offsets.push_back(0)`.

2023-01-05 08:52 UTC, jorgensd approved these changes

2023-01-05 19:01 UTC, garth-wells approved these changes

2023-01-05 19:02 UTC, merged