Update computation of number of components for arbitrary value shape in xdmf_function
FEniCS/dolfinx pull request #2848
Opened 2023-11-01 12:48 UTC by IgorBaratta

Fixes #2843

2023-11-01 13:12 UTC, jorgensd approved these changes

2023-11-02 07:49 UTC, garth-wells requested changes
Looks good. Just one small suggestion.

2023-11-02 07:49 UTC, garth-wells commented on cpp/dolfinx/io/xdmf_function.cpp
> +  if (shape.size() == 0)
```suggestion
  if (shape.empty())
```

2023-11-02 11:45 UTC, garth-wells approved these changes

2023-11-02 13:03 UTC, merged