Check leaf collision
FEniCS/dolfinx pull request #2850
Opened 2023-11-02 07:41 UTC by jorgensd

Reported by @nate-sime 
The following MWE produces the wrong collision for the global_bb_tree
```python
import numpy as np
import dolfinx
from mpi4py import MPI

mesh = dolfinx.mesh.create_unit_square(MPI.COMM_WORLD, 10, 10)

xp = np.array([[100.0, 100.0, 0.0]], dtype=np.double)

tree = dolfinx.geometry.bb_tree(mesh, mesh.topology.dim, padding=1e-4)
global_tree = tree.create_global_tree(mesh.comm)

def pprint(*msg):
    print(f"[{mesh.comm.rank}]: " + " ".join(map(str, msg)), flush=True)

pprint(dolfinx.common.git_commit_hash)
pprint(dolfinx.geometry.compute_collisions_points(tree, xp))
pprint(dolfinx.geometry.compute_collisions_points(global_tree, xp))

```
giving the following in serial:
```bash
[0]: f488f4ecc687d0065315bc9a74939634b18e11ff
[0]: <AdjacencyList> with 1 nodes
  0: []

[0]: <AdjacencyList> with 1 nodes
  0: [0 ]
```
and the correct result in parallel
```bash
[0]: f488f4ecc687d0065315bc9a74939634b18e11ff
[0]: <AdjacencyList> with 1 nodes
  0: []

[0]: <AdjacencyList> with 1 nodes
  0: []

[1]: f488f4ecc687d0065315bc9a74939634b18e11ff
[1]: <AdjacencyList> with 1 nodes
  0: []

[1]: <AdjacencyList> with 1 nodes
  0: []
```

This is due to a bug in `_compute_collisions_point` where we don't check if the leaf node actually collides with the point.
@massimiliano-leoni could you see if this impacts your mesh interpolation (in serial)? As the `global_bb_tree` is used it would add any interpolation point from the other mesh to the process, even if it doesn't collide.

2023-11-02 07:46 UTC, garth-wells requested changes
Could the PR have a more descriptive title?

And could a test be added?

2023-11-02 07:46 UTC, garth-wells commented on cpp/dolfinx/geometry/utils.h
> +    if ((is_leaf(bbox)) && point_in_bbox(tree.get_bbox(next), p))
We and `and` rather than `&&`.

2023-11-02 07:46 UTC, garth-wells commented on cpp/dolfinx/geometry/utils.h
> +  for (std::size_t i = 0; i < collisions.num_nodes(); ++i)
Remove debug output.

2023-11-02 07:46 UTC, garth-wells commented on cpp/dolfinx/geometry/utils.h
> +  for (auto rank : send_sizes)
Remove.

2023-11-02 09:12 UTC, jorgensd commented on cpp/dolfinx/geometry/utils.h
> +  std::cout << "HERE!\n";
```suggestion
```

2023-11-02 09:12 UTC, jorgensd commented on cpp/dolfinx/geometry/utils.h
> +  std::cout << "\n";
```suggestion

```

2023-11-02 12:46 UTC, garth-wells approved these changes

2023-11-02 13:16 UTC, IgorBaratta approved these changes

2023-11-02 13:48 UTC, nate-sime approved these changes

2023-11-03 07:42 UTC, jorgensd commented
@garth-wells  Test added + minor simplification. Feel free to merge this once the CI passes.

2023-11-03 08:58 UTC, merged