Make topology const in `locate_dofs_topological`
FEniCS/dolfinx pull request #2885
Opened 2023-11-10 12:40 UTC by IgorBaratta

2023-11-10 14:59 UTC, jorgensd reviewed
I've got mixed emotions regarding this. If one wants to call `locate_dofs_topological`, this is clearly needed, and it is not clear why we want to force users to call it for this function.

Also note that if we remove it, we need proper error handling (a simple assert isn't enough), as this is not checked in release mode. Then we would need a runtime error saying "Missing connectivity between entities of dim {dim} and {tdim}".

2023-11-10 15:05 UTC, IgorBaratta commented
I think you're right about the error handling.
But other functions already require the user to call `create_connectivity` and `create_entity`, for example `exterior_facet_indices`.

2023-11-10 15:24 UTC, jorgensd commented
> I think you're right about the error handling. But other functions already require the user to call `create_connectivity` and `create_entities`, for example `exterior_facet_indices`.

I know, and if we want to be consistent, we follow your code (and add an appropriate error message). 
I just feel like we should add to the doc-strings what connectives we  expect to ensure that it is easily available information, and that people don't have to run the code and get an error message to know what they need.

2023-11-10 18:25 UTC, francesco-ballarin commented
I for sure agree with all comments above, but I just want to point that these commits did _not_ change a single test or demo. It seems to me that, for all intents and purposes, in any of our actual use cases (C++ demos, C++ tests, python demos, python tests) those entities and connectives are indeed already computed in practice, so most of the users won't even notice this change.

2023-11-10 19:34 UTC, garth-wells requested changes
This is good, but need to change assertions to exceptions.

On Python side we're ok with more implicit behaviour so any required initialisation can happen in the Python layer.

2023-11-10 19:34 UTC, garth-wells commented on cpp/dolfinx/fem/DirichletBC.cpp
>    assert(e_to_c);
Change from assertion to runtime error (and below too).

2023-11-12 15:13 UTC, jorgensd approved these changes

2023-11-12 15:40 UTC, garth-wells approved these changes

2023-11-12 16:42 UTC, merged