Refactor build basic dofmap
FEniCS/dolfinx pull request #2927
Opened 2023-12-08 14:51 UTC by chrisrichardson

Update `build_basic_dofmap` removing some redundant code, and rewriting to generate separate dofmaps for each `ElementDofLayout` passed in. Currently, just returns the first dofmap, related to the first `ElementDofLayout`, but in subsequent PRs, all dofmaps will be passed out.

2023-12-08 17:02 UTC, garth-wells requested changes

2023-12-08 17:02 UTC, garth-wells commented on cpp/dolfinx/fem/dofmapbuilder.cpp
> +                = (d == D) ? c : connectivity[d]->links(c)[e];
Take `connectivity[d].links(c)` outside loop.

2023-12-10 16:11 UTC, jpdean approved these changes

2023-12-10 16:11 UTC, jpdean commented on cpp/dolfinx/fem/dofmapbuilder.cpp
> +    const int elem = i % num_elem_types;
Would `elem_type` be a better name?

2023-12-10 17:04 UTC, chrisrichardson commented on cpp/dolfinx/fem/dofmapbuilder.cpp
> +  const std::size_t D = topology.dim();
To suppress compiler warnings later on when `D` is compared to things which are `size_t`. I don't find it too important, but prefer this to having casts.

2023-12-10 17:05 UTC, chrisrichardson commented on cpp/dolfinx/fem/dofmapbuilder.cpp
> +  std::vector<std::int32_t> num_mesh_entities_local(D + 1, 0);
Naming is always an issue. Do we have a good alternative? `local` is different from `owned` anyway...

2023-12-10 17:05 UTC, chrisrichardson commented on cpp/dolfinx/fem/dofmapbuilder.cpp
>        num_mesh_entities_local[d] = topology.connectivity(d, 0)->num_nodes();
I'll do that, which makes it a bit clearer, since it will explicitly ask for the number of ghosts.

2023-12-10 19:38 UTC, merged