Template distribute entity data
FEniCS/dolfinx pull request #3119
Opened 2024-04-02 20:29 UTC by jorgensd

Would resolve https://github.com/FEniCS/dolfinx/issues/1253

2024-04-02 20:30 UTC, jorgensd commented
@massimiliano-leoni could you test this?:)

2024-04-03 08:07 UTC, jorgensd commented on python/dolfinx/wrappers/io.cpp
> +  // declare_data_types<float>(m);
```suggestion
  declare_data_types<float>(m);
```

2024-04-03 09:16 UTC, garth-wells commented on cpp/dolfinx/io/xdmf_utils.h
> +namespace
Anonymous namespaces should never appear in header files - should only appear in `.cpp` files.

2024-04-03 09:22 UTC, garth-wells requested changes
I would suggest leaving the code in the `.cpp` file and explicitly instantiating for the small number of types that we'll use (at this stage). It's preferable to keep code in the implementation file. This is what we do elsewhere for the mesh.

2024-04-03 10:51 UTC, jorgensd commented on cpp/dolfinx/io/xdmf_utils.h
> +#include <dolfinx/mesh/Topology.h>
```suggestion
```

2024-04-10 10:33 UTC, jorgensd commented
@garth-wells any further changes you would like to see in this PR?

2024-04-15 18:38 UTC, garth-wells approved these changes

2024-04-15 19:19 UTC, merged