Use std::for_each over std::transform for in place operations
FEniCS/dolfinx pull request #3297
Opened 2024-07-04 14:28 UTC by schnellerhase

2024-07-11 20:17 UTC, garth-wells commented
Pure functions are preferable whenever reasonable. Any reason for not using transform from ranges?

2024-07-11 20:28 UTC, schnellerhase commented
`ranges::transform` works analogously - usage of `for_each` improves readability and decreases code complexity, i.e. it is easy to miss that the `transform` version performs an in place operation.

2024-07-12 07:58 UTC, schnellerhase commented
Tried with godbolt (https://godbolt.org/z/5e871aWKG), seems like for optimization `-01` and higher at least the scaling operation produces the same assembly even, not sure how this extends to the more complicated cases - but this is the setting where would hope that pure functions are beneficial, right?

2024-07-12 09:10 UTC, jhale commented
Another big difference in favour `transform` algorithms is that it doesn't demand the operation takes place in order. This is potentially good for performance and/or parallelisation.

I take your point on safety but I think everyone who working at this level is clear that `transform` works as an in place operation.

2024-07-12 19:22 UTC, jhale commented
Could you change the title? We use the PR titles to create Changelogs.

2024-07-12 20:04 UTC, schnellerhase commented
Since this is now just the upgrade for `transform()`, I also added the remaining cases.

2024-07-13 07:17 UTC, garth-wells commented
> Tried with godbolt (https://godbolt.org/z/5e871aWKG), seems like for optimization `-01` and higher at least the scaling operation produces the same assembly even, not sure how this extends to the more complicated cases - but this is the setting where we would hope that pure functions are beneficial, right?

The preference for pure functions is that the logic is simpler and the design models mathematical function. We pass non-const references only when performance is critical.

2024-07-13 08:03 UTC, garth-wells requested changes

2024-07-13 08:03 UTC, garth-wells commented on cpp/dolfinx/mesh/utils.h
> +                         [&igi](std::int32_t sub_x_dof)
```suggestion
                         [&igi](auto sub_x_dof)
```

2024-07-15 04:50 UTC, garth-wells approved these changes

2024-07-15 09:50 UTC, merged