Clarify memory management of returned petsc4py objects.
FEniCS/dolfinx pull request #3329
Opened 2024-08-01 09:56 UTC by jhale

Explicit instructions for handling petsc4py objects memory management.

2024-09-03 13:42 UTC, jorgensd commented
Some context: https://gitlab.com/petsc/petsc/-/issues/1309

2024-09-05 05:53 UTC, jhale commented
These additions are correct at least according to my understanding of the new petsc4py memory management model.

2024-09-05 08:14 UTC, garth-wells requested changes
I've added suggest text that is technically accurate.

2024-09-05 08:14 UTC, garth-wells commented on python/dolfinx/fem/petsc.py
> +    Note:
Suggested text:
```
Note:
    Due to subtle issues in the interaction between petsc4py memory management 
    and the Python garbage collector, it is recommended that the method ``PETSc.Vec.destroy()`` 
    is called on the returned object once the object is no longer required. Note that 
    ``PETSc.Vec.destroy()`` is collective over the object's MPI communicator.  
```

2024-09-10 14:09 UTC, garth-wells approved these changes

2024-09-10 16:26 UTC, merged