Remove std::map from scatter_values in nonmatching interpolation
FEniCS/dolfinx pull request #3396
Opened 2024-09-13 19:45 UTC by jorgensd

Resolves #2419.

2024-09-13 19:45 UTC, jorgensd commented
@massimiliano-leoni do you mind testing this on your huge secret meshes and see that we don't get a regression?
 I can't see how it would regress, as we add some optimizations here to one of the `rank_to_neighbor` maps.

2024-09-14 09:39 UTC, garth-wells requested changes

2024-09-14 09:39 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +    std::vector<std::pair<std::int32_t, std::int32_t>> rank_to_neighbor;
Add `rank_to_neighbor.reserve(in_ranks.size());`

2024-09-14 09:39 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +    std::vector<std::pair<std::int32_t, std::int32_t>> rank_to_neighbor;
`rank_to_neighbor.reserve(out_ranks.size());`

2024-09-14 09:39 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +        [&rank_to_neighbor, &send_sizes, &block_size, &start](auto rank)
```suggestion
        [&rank_to_neighbor, &send_sizes, block_size, &start](auto rank)
```

2024-09-14 09:39 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +    // `out_ranks` are already sorted so ranK_to_neighbor is sorted
```suggestion
    // `out_ranks` is sorted, so rank_to_neighbor will be sorted too
```

2024-09-14 09:39 UTC, garth-wells commented on cpp/dolfinx/fem/interpolate.h
> +    // As `src_ranks` are sorted we can move start in search forward
```suggestion
    // As `src_ranks` is sorted, we can move 'start' in search forward
```

2024-09-14 09:57 UTC, jorgensd commented on cpp/dolfinx/fem/interpolate.h
> +    std::vector<std::pair<std::int32_t, std::int32_t>> rank_to_neighbor;
```suggestion
    std::vector<std::pair<std::int32_t, std::int32_t>> rank_to_neighbor;
    rank_to_neighbor.reserve(in_ranks.size());
```

2024-09-14 09:57 UTC, jorgensd commented on cpp/dolfinx/fem/interpolate.h
> +    std::vector<std::pair<std::int32_t, std::int32_t>> rank_to_neighbor;
```suggestion
    std::vector<std::pair<std::int32_t, std::int32_t>> rank_to_neighbor;
    rank_to_neighbor.reserve(out_ranks.size());
```

2024-09-17 10:02 UTC, garth-wells approved these changes

2024-09-17 10:49 UTC, merged