Add missing docs regarding diagonal
FEniCS/dolfinx pull request #3397
Opened 2024-09-13 20:20 UTC by jorgensd

Also add some notes about when diagonal is set.

2024-09-16 16:24 UTC, jhale requested changes

2024-09-16 16:24 UTC, jhale commented on python/dolfinx/fem/assemble.py
> +        Diagonal entries are only inserted for matrices with the same trial and test space.
Notes are more asides. As this is a critical point I would add it to the argument as 'for constrained degrees of freedom belonging to the same trial and test space.'

2024-09-16 16:25 UTC, jhale submitted a review, later dismissed

2024-09-16 16:25 UTC, jhale commented on python/dolfinx/fem/petsc.py
> +    Note:
Same comment.

2024-09-16 18:17 UTC, jorgensd commented on python/dolfinx/fem/petsc.py
> +
```suggestion
```

2024-09-17 09:39 UTC, garth-wells approved these changes

2024-09-17 09:40 UTC, garth-wells commented
@jhale could you approve this PR if you're happy with it?

2024-09-17 13:49 UTC, merged