Allow access to logged timer data
FEniCS/dolfinx pull request #3487
Opened 2024-10-29 08:13 UTC by garth-wells

2024-10-29 09:06 UTC, jorgensd commented
@garth-wells 
Seems like the `timing` function is broken, as the following doesn't work on nightly
```python
import dolfinx
import time

task = "test"
with dolfinx.common.Timer(task) as timer:
    time.sleep(0.1)

print(dolfinx.common.timing(task))
```
yielding
```bash
Traceback (most recent call last):
  File "/root/shared/debug.py", line 8, in <module>
    print(dolfinx.common.timing(task))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/dolfinx-real/lib/python3.12/dist-packages/dolfinx/common.py", line 48, in timing
    return _cpp.common.timing(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: No timings registered for task "test".
```
Not sure how the tests passed with this.

2024-10-29 13:04 UTC, garth-wells commented
> @garth-wells Seems like the `timing` function is broken, as the following doesn't work on nightly
> 
> ```python
> import dolfinx
> import time
> 
> task = "test"
> with dolfinx.common.Timer(task) as timer:
>     time.sleep(0.1)
> 
> print(dolfinx.common.timing(task))
> ```
> 
> yielding
> 
> ```shell
> Traceback (most recent call last):
>   File "/root/shared/debug.py", line 8, in <module>
>     print(dolfinx.common.timing(task))
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/dolfinx-real/lib/python3.12/dist-packages/dolfinx/common.py", line 48, in timing
>     return _cpp.common.timing(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: No timings registered for task "test".
> ```
> 
> Not sure how the tests passed with this.

See #3488.

2024-10-29 13:50 UTC, jhale requested changes

2024-10-29 13:50 UTC, jhale commented on cpp/dolfinx/common/timing.h
> +std::map<std::string, std::pair<int, double>> timings();
There is a discrepancy in the use of `std::size_t` and `int` between `timing` and `timings`.

2024-10-31 06:02 UTC, jorgensd commented
Could we add docs to the timing routine regarding flush ? Currently the Python routine is undocumented.

2024-10-31 13:40 UTC, jhale approved these changes

2024-10-31 14:06 UTC, merged