Resolve #3519
FEniCS/dolfinx pull request #3520
Opened 2024-11-19 21:00 UTC by jorgensd

2024-11-19 21:32 UTC, garth-wells requested changes
This fix is at the wrong level. It needs to be done at a high level when the appropriate constructor is called.

2024-11-19 21:52 UTC, garth-wells commented
See https://github.com/FEniCS/basix/pull/882.

2024-11-19 21:56 UTC, jorgensd commented
> See [FEniCS/basix#882](https://github.com/FEniCS/basix/pull/882).

This doesn’t resolve the issue, as you then forces the external library to handle two different cases: 
If they only have a single elements, go down one code path, if there are multiple, do something completely different.

this is because one relies on .sub(i) for interpolation, boundary condition etc.

2024-11-21 16:10 UTC, RemDelaporteMathurin approved these changes

2024-11-21 21:19 UTC, garth-wells approved these changes

2024-11-21 22:08 UTC, merged